default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 1234
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: insurance_mgt_development

test:
  <<: *default
  database: insurance_mgt_test

production:
  <<: *default
  database: insurance_mgt_production
  username: insurance_mgt
  password: <%= ENV['INSURANCE_MGT_DATABASE_PASSWORD'] %>